version: '3.1'

services:

  mongo:
    image: mongo:3.6.3
    container_name: mongoDB
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: handy~soft
    volumes:
        - ~/mongoDB/data:/data/db
        - ~/mongoDB/configdb:/data/configdb
    ports:
        - 27017:27017
        
  mongo-express:
    image: mongo-express
    container_name: mongoExpress
    restart: always
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: handy~soft

